# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PlanetJ1GUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1737, 946)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 50, 171, 34))
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 100, 937, 508))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.r5c0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r5c0.setObjectName("r5c0")
        self.gridLayout.addWidget(self.r5c0, 5, 0, 1, 1)
        self.r0c7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r0c7.setObjectName("r0c7")
        self.gridLayout.addWidget(self.r0c7, 0, 7, 1, 1)
        self.r4c2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r4c2.setObjectName("r4c2")
        self.gridLayout.addWidget(self.r4c2, 4, 2, 1, 1)
        self.r2c6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r2c6.setObjectName("r2c6")
        self.gridLayout.addWidget(self.r2c6, 2, 6, 1, 1)
        self.r4c1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r4c1.setObjectName("r4c1")
        self.gridLayout.addWidget(self.r4c1, 4, 1, 1, 1)
        self.r0c10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r0c10.setObjectName("r0c10")
        self.gridLayout.addWidget(self.r0c10, 0, 10, 1, 1)
        self.r0c2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r0c2.setObjectName("r0c2")
        self.gridLayout.addWidget(self.r0c2, 0, 2, 1, 1)
        self.r0c1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r0c1.setObjectName("r0c1")
        self.gridLayout.addWidget(self.r0c1, 0, 1, 1, 1)
        self.r1c1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r1c1.setObjectName("r1c1")
        self.gridLayout.addWidget(self.r1c1, 1, 1, 1, 1)
        self.r0c0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r0c0.setObjectName("r0c0")
        self.gridLayout.addWidget(self.r0c0, 0, 0, 1, 1)
        self.r6c0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r6c0.setObjectName("r6c0")
        self.gridLayout.addWidget(self.r6c0, 6, 0, 1, 1)
        self.r0c9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r0c9.setObjectName("r0c9")
        self.gridLayout.addWidget(self.r0c9, 0, 9, 1, 1)
        self.r1c6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r1c6.setObjectName("r1c6")
        self.gridLayout.addWidget(self.r1c6, 1, 6, 1, 1)
        self.r1c0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r1c0.setObjectName("r1c0")
        self.gridLayout.addWidget(self.r1c0, 1, 0, 1, 1)
        self.r0c8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r0c8.setObjectName("r0c8")
        self.gridLayout.addWidget(self.r0c8, 0, 8, 1, 1)
        self.r1c3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r1c3.setObjectName("r1c3")
        self.gridLayout.addWidget(self.r1c3, 1, 3, 1, 1)
        self.r5c3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r5c3.setObjectName("r5c3")
        self.gridLayout.addWidget(self.r5c3, 5, 3, 1, 1)
        self.r5c6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r5c6.setObjectName("r5c6")
        self.gridLayout.addWidget(self.r5c6, 5, 6, 1, 1)
        self.r6c4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r6c4.setObjectName("r6c4")
        self.gridLayout.addWidget(self.r6c4, 6, 4, 1, 1)
        self.r2c5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r2c5.setObjectName("r2c5")
        self.gridLayout.addWidget(self.r2c5, 2, 5, 1, 1)
        self.r2c1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r2c1.setObjectName("r2c1")
        self.gridLayout.addWidget(self.r2c1, 2, 1, 1, 1)
        self.r3c3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r3c3.setObjectName("r3c3")
        self.gridLayout.addWidget(self.r3c3, 3, 3, 1, 1)
        self.r5c2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r5c2.setObjectName("r5c2")
        self.gridLayout.addWidget(self.r5c2, 5, 2, 1, 1)
        self.r2c0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r2c0.setObjectName("r2c0")
        self.gridLayout.addWidget(self.r2c0, 2, 0, 1, 1)
        self.r4c5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r4c5.setObjectName("r4c5")
        self.gridLayout.addWidget(self.r4c5, 4, 5, 1, 1)
        self.r5c1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r5c1.setObjectName("r5c1")
        self.gridLayout.addWidget(self.r5c1, 5, 1, 1, 1)
        self.r1c5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r1c5.setObjectName("r1c5")
        self.gridLayout.addWidget(self.r1c5, 1, 5, 1, 1)
        self.r3c6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r3c6.setObjectName("r3c6")
        self.gridLayout.addWidget(self.r3c6, 3, 6, 1, 1)
        self.r2c3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r2c3.setObjectName("r2c3")
        self.gridLayout.addWidget(self.r2c3, 2, 3, 1, 1)
        self.r3c0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r3c0.setObjectName("r3c0")
        self.gridLayout.addWidget(self.r3c0, 3, 0, 1, 1)
        self.r4c4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r4c4.setObjectName("r4c4")
        self.gridLayout.addWidget(self.r4c4, 4, 4, 1, 1)
        self.r2c2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r2c2.setObjectName("r2c2")
        self.gridLayout.addWidget(self.r2c2, 2, 2, 1, 1)
        self.r4c6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r4c6.setObjectName("r4c6")
        self.gridLayout.addWidget(self.r4c6, 4, 6, 1, 1)
        self.r4c0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r4c0.setObjectName("r4c0")
        self.gridLayout.addWidget(self.r4c0, 4, 0, 1, 1)
        self.r5c4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r5c4.setObjectName("r5c4")
        self.gridLayout.addWidget(self.r5c4, 5, 4, 1, 1)
        self.r5c5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r5c5.setObjectName("r5c5")
        self.gridLayout.addWidget(self.r5c5, 5, 5, 1, 1)
        self.r6c3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r6c3.setObjectName("r6c3")
        self.gridLayout.addWidget(self.r6c3, 6, 3, 1, 1)
        self.r1c2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r1c2.setObjectName("r1c2")
        self.gridLayout.addWidget(self.r1c2, 1, 2, 1, 1)
        self.r6c6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r6c6.setObjectName("r6c6")
        self.gridLayout.addWidget(self.r6c6, 6, 6, 1, 1)
        self.r0c4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r0c4.setObjectName("r0c4")
        self.gridLayout.addWidget(self.r0c4, 0, 4, 1, 1)
        self.r6c2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r6c2.setObjectName("r6c2")
        self.gridLayout.addWidget(self.r6c2, 6, 2, 1, 1)
        self.r2c4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r2c4.setObjectName("r2c4")
        self.gridLayout.addWidget(self.r2c4, 2, 4, 1, 1)
        self.r0c3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r0c3.setObjectName("r0c3")
        self.gridLayout.addWidget(self.r0c3, 0, 3, 1, 1)
        self.r4c3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r4c3.setObjectName("r4c3")
        self.gridLayout.addWidget(self.r4c3, 4, 3, 1, 1)
        self.r3c1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r3c1.setObjectName("r3c1")
        self.gridLayout.addWidget(self.r3c1, 3, 1, 1, 1)
        self.r3c2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r3c2.setObjectName("r3c2")
        self.gridLayout.addWidget(self.r3c2, 3, 2, 1, 1)
        self.r1c4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r1c4.setObjectName("r1c4")
        self.gridLayout.addWidget(self.r1c4, 1, 4, 1, 1)
        self.r6c1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r6c1.setObjectName("r6c1")
        self.gridLayout.addWidget(self.r6c1, 6, 1, 1, 1)
        self.r3c4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r3c4.setObjectName("r3c4")
        self.gridLayout.addWidget(self.r3c4, 3, 4, 1, 1)
        self.r3c5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r3c5.setObjectName("r3c5")
        self.gridLayout.addWidget(self.r3c5, 3, 5, 1, 1)
        self.r6c5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r6c5.setObjectName("r6c5")
        self.gridLayout.addWidget(self.r6c5, 6, 5, 1, 1)
        self.r0c5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r0c5.setObjectName("r0c5")
        self.gridLayout.addWidget(self.r0c5, 0, 5, 1, 1)
        self.r0c6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r0c6.setObjectName("r0c6")
        self.gridLayout.addWidget(self.r0c6, 0, 6, 1, 1)
        self.r7c0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r7c0.setObjectName("r7c0")
        self.gridLayout.addWidget(self.r7c0, 7, 0, 1, 1)
        self.r9c0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r9c0.setObjectName("r9c0")
        self.gridLayout.addWidget(self.r9c0, 9, 0, 1, 1)
        self.r8c0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r8c0.setObjectName("r8c0")
        self.gridLayout.addWidget(self.r8c0, 8, 0, 1, 1)
        self.r10c0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r10c0.setObjectName("r10c0")
        self.gridLayout.addWidget(self.r10c0, 10, 0, 1, 1)
        self.r1c7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r1c7.setObjectName("r1c7")
        self.gridLayout.addWidget(self.r1c7, 1, 7, 1, 1)
        self.r1c8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r1c8.setObjectName("r1c8")
        self.gridLayout.addWidget(self.r1c8, 1, 8, 1, 1)
        self.r1c9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r1c9.setObjectName("r1c9")
        self.gridLayout.addWidget(self.r1c9, 1, 9, 1, 1)
        self.r1c10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r1c10.setObjectName("r1c10")
        self.gridLayout.addWidget(self.r1c10, 1, 10, 1, 1)
        self.r2c7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r2c7.setObjectName("r2c7")
        self.gridLayout.addWidget(self.r2c7, 2, 7, 1, 1)
        self.r2c8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r2c8.setObjectName("r2c8")
        self.gridLayout.addWidget(self.r2c8, 2, 8, 1, 1)
        self.r2c9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r2c9.setObjectName("r2c9")
        self.gridLayout.addWidget(self.r2c9, 2, 9, 1, 1)
        self.r2c10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r2c10.setObjectName("r2c10")
        self.gridLayout.addWidget(self.r2c10, 2, 10, 1, 1)
        self.r3c7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r3c7.setObjectName("r3c7")
        self.gridLayout.addWidget(self.r3c7, 3, 7, 1, 1)
        self.r3c8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r3c8.setObjectName("r3c8")
        self.gridLayout.addWidget(self.r3c8, 3, 8, 1, 1)
        self.r3c9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r3c9.setObjectName("r3c9")
        self.gridLayout.addWidget(self.r3c9, 3, 9, 1, 1)
        self.r3c10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r3c10.setObjectName("r3c10")
        self.gridLayout.addWidget(self.r3c10, 3, 10, 1, 1)
        self.r4c7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r4c7.setObjectName("r4c7")
        self.gridLayout.addWidget(self.r4c7, 4, 7, 1, 1)
        self.r4c8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r4c8.setObjectName("r4c8")
        self.gridLayout.addWidget(self.r4c8, 4, 8, 1, 1)
        self.r4c9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r4c9.setObjectName("r4c9")
        self.gridLayout.addWidget(self.r4c9, 4, 9, 1, 1)
        self.r4c10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r4c10.setObjectName("r4c10")
        self.gridLayout.addWidget(self.r4c10, 4, 10, 1, 1)
        self.r5c7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r5c7.setObjectName("r5c7")
        self.gridLayout.addWidget(self.r5c7, 5, 7, 1, 1)
        self.r5c8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r5c8.setObjectName("r5c8")
        self.gridLayout.addWidget(self.r5c8, 5, 8, 1, 1)
        self.r5c9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r5c9.setObjectName("r5c9")
        self.gridLayout.addWidget(self.r5c9, 5, 9, 1, 1)
        self.r5c10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r5c10.setObjectName("r5c10")
        self.gridLayout.addWidget(self.r5c10, 5, 10, 1, 1)
        self.r6c7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r6c7.setObjectName("r6c7")
        self.gridLayout.addWidget(self.r6c7, 6, 7, 1, 1)
        self.r6c8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r6c8.setObjectName("r6c8")
        self.gridLayout.addWidget(self.r6c8, 6, 8, 1, 1)
        self.r6c9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r6c9.setObjectName("r6c9")
        self.gridLayout.addWidget(self.r6c9, 6, 9, 1, 1)
        self.r6c10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r6c10.setObjectName("r6c10")
        self.gridLayout.addWidget(self.r6c10, 6, 10, 1, 1)
        self.r7c1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r7c1.setObjectName("r7c1")
        self.gridLayout.addWidget(self.r7c1, 7, 1, 1, 1)
        self.r7c2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r7c2.setObjectName("r7c2")
        self.gridLayout.addWidget(self.r7c2, 7, 2, 1, 1)
        self.r7c3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r7c3.setObjectName("r7c3")
        self.gridLayout.addWidget(self.r7c3, 7, 3, 1, 1)
        self.r7c4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r7c4.setObjectName("r7c4")
        self.gridLayout.addWidget(self.r7c4, 7, 4, 1, 1)
        self.r7c5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r7c5.setObjectName("r7c5")
        self.gridLayout.addWidget(self.r7c5, 7, 5, 1, 1)
        self.r7c6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r7c6.setObjectName("r7c6")
        self.gridLayout.addWidget(self.r7c6, 7, 6, 1, 1)
        self.r7c7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r7c7.setObjectName("r7c7")
        self.gridLayout.addWidget(self.r7c7, 7, 7, 1, 1)
        self.r8c1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r8c1.setObjectName("r8c1")
        self.gridLayout.addWidget(self.r8c1, 8, 1, 1, 1)
        self.r8c2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r8c2.setObjectName("r8c2")
        self.gridLayout.addWidget(self.r8c2, 8, 2, 1, 1)
        self.r8c3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r8c3.setObjectName("r8c3")
        self.gridLayout.addWidget(self.r8c3, 8, 3, 1, 1)
        self.r8c4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r8c4.setObjectName("r8c4")
        self.gridLayout.addWidget(self.r8c4, 8, 4, 1, 1)
        self.r8c5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r8c5.setObjectName("r8c5")
        self.gridLayout.addWidget(self.r8c5, 8, 5, 1, 1)
        self.r8c6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r8c6.setObjectName("r8c6")
        self.gridLayout.addWidget(self.r8c6, 8, 6, 1, 1)
        self.r8c7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r8c7.setObjectName("r8c7")
        self.gridLayout.addWidget(self.r8c7, 8, 7, 1, 1)
        self.r9c1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r9c1.setObjectName("r9c1")
        self.gridLayout.addWidget(self.r9c1, 9, 1, 1, 1)
        self.r9c2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r9c2.setObjectName("r9c2")
        self.gridLayout.addWidget(self.r9c2, 9, 2, 1, 1)
        self.r9c3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r9c3.setObjectName("r9c3")
        self.gridLayout.addWidget(self.r9c3, 9, 3, 1, 1)
        self.r9c4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r9c4.setObjectName("r9c4")
        self.gridLayout.addWidget(self.r9c4, 9, 4, 1, 1)
        self.r9c5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r9c5.setObjectName("r9c5")
        self.gridLayout.addWidget(self.r9c5, 9, 5, 1, 1)
        self.r9c6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r9c6.setObjectName("r9c6")
        self.gridLayout.addWidget(self.r9c6, 9, 6, 1, 1)
        self.r9c7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r9c7.setObjectName("r9c7")
        self.gridLayout.addWidget(self.r9c7, 9, 7, 1, 1)
        self.r10c1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r10c1.setObjectName("r10c1")
        self.gridLayout.addWidget(self.r10c1, 10, 1, 1, 1)
        self.r10c2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r10c2.setObjectName("r10c2")
        self.gridLayout.addWidget(self.r10c2, 10, 2, 1, 1)
        self.r10c3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r10c3.setObjectName("r10c3")
        self.gridLayout.addWidget(self.r10c3, 10, 3, 1, 1)
        self.r10c4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r10c4.setObjectName("r10c4")
        self.gridLayout.addWidget(self.r10c4, 10, 4, 1, 1)
        self.r10c5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r10c5.setObjectName("r10c5")
        self.gridLayout.addWidget(self.r10c5, 10, 5, 1, 1)
        self.r10c6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r10c6.setObjectName("r10c6")
        self.gridLayout.addWidget(self.r10c6, 10, 6, 1, 1)
        self.r10c7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r10c7.setObjectName("r10c7")
        self.gridLayout.addWidget(self.r10c7, 10, 7, 1, 1)
        self.r7c8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r7c8.setObjectName("r7c8")
        self.gridLayout.addWidget(self.r7c8, 7, 8, 1, 1)
        self.r7c9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r7c9.setObjectName("r7c9")
        self.gridLayout.addWidget(self.r7c9, 7, 9, 1, 1)
        self.r7c10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r7c10.setObjectName("r7c10")
        self.gridLayout.addWidget(self.r7c10, 7, 10, 1, 1)
        self.r8c8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r8c8.setObjectName("r8c8")
        self.gridLayout.addWidget(self.r8c8, 8, 8, 1, 1)
        self.r9c8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r9c8.setObjectName("r9c8")
        self.gridLayout.addWidget(self.r9c8, 9, 8, 1, 1)
        self.r8c9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r8c9.setObjectName("r8c9")
        self.gridLayout.addWidget(self.r8c9, 8, 9, 1, 1)
        self.r8c10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r8c10.setObjectName("r8c10")
        self.gridLayout.addWidget(self.r8c10, 8, 10, 1, 1)
        self.r10c8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r10c8.setObjectName("r10c8")
        self.gridLayout.addWidget(self.r10c8, 10, 8, 1, 1)
        self.r9c9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r9c9.setObjectName("r9c9")
        self.gridLayout.addWidget(self.r9c9, 9, 9, 1, 1)
        self.r9c10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r9c10.setObjectName("r9c10")
        self.gridLayout.addWidget(self.r9c10, 9, 10, 1, 1)
        self.r10c9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r10c9.setObjectName("r10c9")
        self.gridLayout.addWidget(self.r10c9, 10, 9, 1, 1)
        self.r10c10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.r10c10.setObjectName("r10c10")
        self.gridLayout.addWidget(self.r10c10, 10, 10, 1, 1)
        self.infoList = QtWidgets.QListWidget(self.centralwidget)
        self.infoList.setGeometry(QtCore.QRect(60, 670, 571, 171))
        self.infoList.setObjectName("infoList")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 620, 151, 34))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(680, 620, 107, 34))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1030, 30, 51, 34))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1200, 30, 51, 34))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1380, 30, 61, 34))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(280, 50, 61, 34))
        self.label_8.setObjectName("label_8")
        self.minLabel = QtWidgets.QLabel(self.centralwidget)
        self.minLabel.setGeometry(QtCore.QRect(1090, 30, 91, 34))
        self.minLabel.setObjectName("minLabel")
        self.gasLabel = QtWidgets.QLabel(self.centralwidget)
        self.gasLabel.setGeometry(QtCore.QRect(1260, 30, 101, 34))
        self.gasLabel.setObjectName("gasLabel")
        self.nrgLabel = QtWidgets.QLabel(self.centralwidget)
        self.nrgLabel.setGeometry(QtCore.QRect(1450, 30, 91, 34))
        self.nrgLabel.setObjectName("nrgLabel")
        self.statusList = QtWidgets.QListWidget(self.centralwidget)
        self.statusList.setGeometry(QtCore.QRect(690, 670, 301, 171))
        self.statusList.setObjectName("statusList")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(1030, 100, 681, 771))
        self.groupBox_2.setObjectName("groupBox_2")
        self.doButton = QtWidgets.QPushButton(self.groupBox_2)
        self.doButton.setGeometry(QtCore.QRect(310, 10, 151, 46))
        self.doButton.setObjectName("doButton")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setGeometry(QtCore.QRect(0, 440, 681, 331))
        self.groupBox.setObjectName("groupBox")
        self.upButton = QtWidgets.QPushButton(self.groupBox)
        self.upButton.setGeometry(QtCore.QRect(160, 40, 153, 61))
        self.upButton.setObjectName("upButton")
        self.leftButton = QtWidgets.QPushButton(self.groupBox)
        self.leftButton.setGeometry(QtCore.QRect(70, 120, 153, 61))
        self.leftButton.setObjectName("leftButton")
        self.rightButton = QtWidgets.QPushButton(self.groupBox)
        self.rightButton.setGeometry(QtCore.QRect(250, 120, 153, 61))
        self.rightButton.setObjectName("rightButton")
        self.downButton = QtWidgets.QPushButton(self.groupBox)
        self.downButton.setGeometry(QtCore.QRect(160, 200, 153, 61))
        self.downButton.setObjectName("downButton")
        self.nextBuilder = QtWidgets.QPushButton(self.groupBox)
        self.nextBuilder.setGeometry(QtCore.QRect(0, 60, 151, 46))
        self.nextBuilder.setObjectName("nextBuilder")
        self.nextWorker = QtWidgets.QPushButton(self.groupBox)
        self.nextWorker.setGeometry(QtCore.QRect(320, 60, 153, 46))
        self.nextWorker.setObjectName("nextWorker")
        self.nextSoldier = QtWidgets.QPushButton(self.groupBox)
        self.nextSoldier.setGeometry(QtCore.QRect(0, 190, 151, 46))
        self.nextSoldier.setObjectName("nextSoldier")
        self.nextTank = QtWidgets.QPushButton(self.groupBox)
        self.nextTank.setGeometry(QtCore.QRect(320, 190, 151, 46))
        self.nextTank.setObjectName("nextTank")
        self.nextPlane = QtWidgets.QPushButton(self.groupBox)
        self.nextPlane.setGeometry(QtCore.QRect(320, 250, 151, 46))
        self.nextPlane.setObjectName("nextPlane")
        self.nextBoat = QtWidgets.QPushButton(self.groupBox)
        self.nextBoat.setGeometry(QtCore.QRect(0, 250, 151, 46))
        self.nextBoat.setObjectName("nextBoat")
        self.viewMode = QtWidgets.QPushButton(self.groupBox)
        self.viewMode.setGeometry(QtCore.QRect(160, 270, 151, 46))
        self.viewMode.setObjectName("viewMode")
        self.nextFactory = QtWidgets.QPushButton(self.groupBox)
        self.nextFactory.setGeometry(QtCore.QRect(500, 190, 153, 46))
        self.nextFactory.setObjectName("nextFactory")
        self.nextHQ = QtWidgets.QPushButton(self.groupBox)
        self.nextHQ.setGeometry(QtCore.QRect(500, 60, 153, 46))
        self.nextHQ.setObjectName("nextHQ")
        self.nextBase = QtWidgets.QPushButton(self.groupBox)
        self.nextBase.setGeometry(QtCore.QRect(500, 250, 153, 46))
        self.nextBase.setObjectName("nextBase")
        self.commandList = QtWidgets.QListWidget(self.groupBox_2)
        self.commandList.setGeometry(QtCore.QRect(10, 70, 661, 351))
        self.commandList.setObjectName("commandList")
        self.timeLabel = QtWidgets.QLabel(self.centralwidget)
        self.timeLabel.setGeometry(QtCore.QRect(350, 50, 181, 34))
        self.timeLabel.setObjectName("timeLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1737, 40))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.actionOptions = QtWidgets.QAction(MainWindow)
        self.actionOptions.setObjectName("actionOptions")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionOptions)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PlanetJ1Qt"))
        self.label.setText(_translate("MainWindow", "PlanetJ1 Alpha"))
        self.r5c0.setText(_translate("MainWindow", "B"))
        self.r0c7.setText(_translate("MainWindow", "B"))
        self.r4c2.setText(_translate("MainWindow", "B"))
        self.r2c6.setText(_translate("MainWindow", "B"))
        self.r4c1.setText(_translate("MainWindow", "B"))
        self.r0c10.setText(_translate("MainWindow", "B"))
        self.r0c2.setText(_translate("MainWindow", "B"))
        self.r0c1.setText(_translate("MainWindow", "B"))
        self.r1c1.setText(_translate("MainWindow", "B"))
        self.r0c0.setText(_translate("MainWindow", "B"))
        self.r6c0.setText(_translate("MainWindow", "B"))
        self.r0c9.setText(_translate("MainWindow", "B"))
        self.r1c6.setText(_translate("MainWindow", "B"))
        self.r1c0.setText(_translate("MainWindow", "B"))
        self.r0c8.setText(_translate("MainWindow", "B"))
        self.r1c3.setText(_translate("MainWindow", "B"))
        self.r5c3.setText(_translate("MainWindow", "B"))
        self.r5c6.setText(_translate("MainWindow", "B"))
        self.r6c4.setText(_translate("MainWindow", "B"))
        self.r2c5.setText(_translate("MainWindow", "B"))
        self.r2c1.setText(_translate("MainWindow", "B"))
        self.r3c3.setText(_translate("MainWindow", "B"))
        self.r5c2.setText(_translate("MainWindow", "B"))
        self.r2c0.setText(_translate("MainWindow", "B"))
        self.r4c5.setText(_translate("MainWindow", "B"))
        self.r5c1.setText(_translate("MainWindow", "B"))
        self.r1c5.setText(_translate("MainWindow", "B"))
        self.r3c6.setText(_translate("MainWindow", "B"))
        self.r2c3.setText(_translate("MainWindow", "B"))
        self.r3c0.setText(_translate("MainWindow", "B"))
        self.r4c4.setText(_translate("MainWindow", "B"))
        self.r2c2.setText(_translate("MainWindow", "B"))
        self.r4c6.setText(_translate("MainWindow", "B"))
        self.r4c0.setText(_translate("MainWindow", "B"))
        self.r5c4.setText(_translate("MainWindow", "B"))
        self.r5c5.setText(_translate("MainWindow", "B"))
        self.r6c3.setText(_translate("MainWindow", "B"))
        self.r1c2.setText(_translate("MainWindow", "B"))
        self.r6c6.setText(_translate("MainWindow", "B"))
        self.r0c4.setText(_translate("MainWindow", "B"))
        self.r6c2.setText(_translate("MainWindow", "B"))
        self.r2c4.setText(_translate("MainWindow", "B"))
        self.r0c3.setText(_translate("MainWindow", "B"))
        self.r4c3.setText(_translate("MainWindow", "B"))
        self.r3c1.setText(_translate("MainWindow", "B"))
        self.r3c2.setText(_translate("MainWindow", "B"))
        self.r1c4.setText(_translate("MainWindow", "B"))
        self.r6c1.setText(_translate("MainWindow", "B"))
        self.r3c4.setText(_translate("MainWindow", "B"))
        self.r3c5.setText(_translate("MainWindow", "B"))
        self.r6c5.setText(_translate("MainWindow", "B"))
        self.r0c5.setText(_translate("MainWindow", "B"))
        self.r0c6.setText(_translate("MainWindow", "B"))
        self.r7c0.setText(_translate("MainWindow", "B"))
        self.r9c0.setText(_translate("MainWindow", "B"))
        self.r8c0.setText(_translate("MainWindow", "B"))
        self.r10c0.setText(_translate("MainWindow", "B"))
        self.r1c7.setText(_translate("MainWindow", "B"))
        self.r1c8.setText(_translate("MainWindow", "B"))
        self.r1c9.setText(_translate("MainWindow", "B"))
        self.r1c10.setText(_translate("MainWindow", "B"))
        self.r2c7.setText(_translate("MainWindow", "B"))
        self.r2c8.setText(_translate("MainWindow", "B"))
        self.r2c9.setText(_translate("MainWindow", "B"))
        self.r2c10.setText(_translate("MainWindow", "B"))
        self.r3c7.setText(_translate("MainWindow", "B"))
        self.r3c8.setText(_translate("MainWindow", "B"))
        self.r3c9.setText(_translate("MainWindow", "B"))
        self.r3c10.setText(_translate("MainWindow", "B"))
        self.r4c7.setText(_translate("MainWindow", "B"))
        self.r4c8.setText(_translate("MainWindow", "B"))
        self.r4c9.setText(_translate("MainWindow", "B"))
        self.r4c10.setText(_translate("MainWindow", "B"))
        self.r5c7.setText(_translate("MainWindow", "B"))
        self.r5c8.setText(_translate("MainWindow", "B"))
        self.r5c9.setText(_translate("MainWindow", "B"))
        self.r5c10.setText(_translate("MainWindow", "B"))
        self.r6c7.setText(_translate("MainWindow", "B"))
        self.r6c8.setText(_translate("MainWindow", "B"))
        self.r6c9.setText(_translate("MainWindow", "B"))
        self.r6c10.setText(_translate("MainWindow", "B"))
        self.r7c1.setText(_translate("MainWindow", "B"))
        self.r7c2.setText(_translate("MainWindow", "B"))
        self.r7c3.setText(_translate("MainWindow", "B"))
        self.r7c4.setText(_translate("MainWindow", "B"))
        self.r7c5.setText(_translate("MainWindow", "B"))
        self.r7c6.setText(_translate("MainWindow", "B"))
        self.r7c7.setText(_translate("MainWindow", "B"))
        self.r8c1.setText(_translate("MainWindow", "B"))
        self.r8c2.setText(_translate("MainWindow", "B"))
        self.r8c3.setText(_translate("MainWindow", "B"))
        self.r8c4.setText(_translate("MainWindow", "B"))
        self.r8c5.setText(_translate("MainWindow", "B"))
        self.r8c6.setText(_translate("MainWindow", "B"))
        self.r8c7.setText(_translate("MainWindow", "B"))
        self.r9c1.setText(_translate("MainWindow", "B"))
        self.r9c2.setText(_translate("MainWindow", "B"))
        self.r9c3.setText(_translate("MainWindow", "B"))
        self.r9c4.setText(_translate("MainWindow", "B"))
        self.r9c5.setText(_translate("MainWindow", "B"))
        self.r9c6.setText(_translate("MainWindow", "B"))
        self.r9c7.setText(_translate("MainWindow", "B"))
        self.r10c1.setText(_translate("MainWindow", "B"))
        self.r10c2.setText(_translate("MainWindow", "B"))
        self.r10c3.setText(_translate("MainWindow", "B"))
        self.r10c4.setText(_translate("MainWindow", "B"))
        self.r10c5.setText(_translate("MainWindow", "B"))
        self.r10c6.setText(_translate("MainWindow", "B"))
        self.r10c7.setText(_translate("MainWindow", "B"))
        self.r7c8.setText(_translate("MainWindow", "B"))
        self.r7c9.setText(_translate("MainWindow", "B"))
        self.r7c10.setText(_translate("MainWindow", "B"))
        self.r8c8.setText(_translate("MainWindow", "B"))
        self.r9c8.setText(_translate("MainWindow", "B"))
        self.r8c9.setText(_translate("MainWindow", "B"))
        self.r8c10.setText(_translate("MainWindow", "B"))
        self.r10c8.setText(_translate("MainWindow", "B"))
        self.r9c9.setText(_translate("MainWindow", "B"))
        self.r9c10.setText(_translate("MainWindow", "B"))
        self.r10c9.setText(_translate("MainWindow", "B"))
        self.r10c10.setText(_translate("MainWindow", "B"))
        self.label_2.setText(_translate("MainWindow", "Information:"))
        self.label_3.setText(_translate("MainWindow", "Status:"))
        self.label_5.setText(_translate("MainWindow", "Min:"))
        self.label_6.setText(_translate("MainWindow", "Gas:"))
        self.label_7.setText(_translate("MainWindow", "NRG:"))
        self.label_8.setText(_translate("MainWindow", "Time:"))
        self.minLabel.setText(_translate("MainWindow", "???"))
        self.gasLabel.setText(_translate("MainWindow", "???"))
        self.nrgLabel.setText(_translate("MainWindow", "???"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Commander X16:"))
        self.doButton.setText(_translate("MainWindow", "Make It So!"))
        self.groupBox.setTitle(_translate("MainWindow", "Controls:"))
        self.upButton.setText(_translate("MainWindow", "^ Up ^"))
        self.leftButton.setText(_translate("MainWindow", "<---Left"))
        self.rightButton.setText(_translate("MainWindow", "Right--->"))
        self.downButton.setText(_translate("MainWindow", "v Down v"))
        self.nextBuilder.setText(_translate("MainWindow", "Next Builder"))
        self.nextWorker.setText(_translate("MainWindow", "Next Worker"))
        self.nextSoldier.setText(_translate("MainWindow", "Next Soldier"))
        self.nextTank.setText(_translate("MainWindow", "Next Tank"))
        self.nextPlane.setText(_translate("MainWindow", "Next Plane"))
        self.nextBoat.setText(_translate("MainWindow", "Next Boat"))
        self.viewMode.setText(_translate("MainWindow", "View Mode"))
        self.nextFactory.setText(_translate("MainWindow", "Next Factory"))
        self.nextHQ.setText(_translate("MainWindow", "Next HQ"))
        self.nextBase.setText(_translate("MainWindow", "Next Base"))
        self.timeLabel.setText(_translate("MainWindow", "???"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.action2.setText(_translate("MainWindow", "2"))
        self.actionAbout.setText(_translate("MainWindow", "About..."))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        self.action_2.setText(_translate("MainWindow", "----------------"))
        self.actionOptions.setText(_translate("MainWindow", "Options..."))

